### ISSUE TITLE
Can't build project, some dependencies not found

### ISSUE THREAD

**Issue by Mohamadhassan98** [kotlin-orm/ktorm-example-spring-boot#10]
Hi there.
I'm trying to use this project to configure my spring boot project.
I've started by comparing your project with mine, adding dependencies one by one.
Some dependencies are missing in the repository (or there is some misconfiguration that I don't know).

At the end, I'd cloned your repo to see if it runs.
The missing dependencies are still missing and the project can't be ran.
I have problem with `org.ktorm:ktorm:3.7.0-SNAPSHOT` dependencies, this version does not exists.
Changing this to latest present version (3.6.0) fixes that.
Then the dependency `org.ktorm:ktorm-ksp-annotations` doesn't exist at all.

I confused about the gradle dependencies.

Can you help me run it?

**Comment by vincentlauvlwj** [comment]
https://github.com/kotlin-orm/ktorm-example-spring-boot/issues/9#issuecomment-1672426025

**Comment by vincentlauvlwj** [comment]
Fixed.
