### ISSUE TITLE
java.lang.UnsupportedOperationException: Transaction is managed by Spring, please use Spring's @Transactional annotation instead.

### ISSUE THREAD

**Issue by aohanhongzhi** [kotlin-orm/ktorm-example-spring-boot#2]
java.lang.UnsupportedOperationException: Transaction is managed by Spring, please use Spring's @Transactional annotation instead.

when I post http quest to localhost:8080/departments/create?name=aa&location=111

**Comment by vincentlauvlwj** [comment]
Thank you for your feedback. This is a bug. I've upgraded Ktorm to version 2.7.2 to fix it.
