### ISSUE TITLE
Usage of Ktorm in another github project for reference.

### ISSUE THREAD

**Issue by martin-jamszolik** [kotlin-orm/ktorm-example-spring-boot#5]
Hi There,
I figured I share my project as a reference for another real ktorm example.
https://github.com/martin-jamszolik/vivid-web-app/tree/master/src/main/kotlin/com/vivid/graff/shared

Just want to give credit to KTORM project for providing such a great database framework.
I used Ktorm to help me implement a kind of a hybrid "Repository Pattern". 
It's great how Ktorm wraps RDBMS concepts so elegantly and cleanly.  
Feel free to use this reference as you see fit. 
Thanks

**Comment by vincentlauvlwj** [comment]
Thank you, I'm glad this project can help you.
