### ISSUE TITLE
Base project not compiling

### ISSUE THREAD

**Issue by giovanni-orciuolo** [kotlin-orm/ktorm-example-spring-boot#9]
Hello! I'm trying out this project to see if it would be possible to integrate Spring with Ktorm.

I cloned it on my machine, but it fails to compile because `EmployeeDao` requires both `Employee` and `Employees` to be defined, but at the moment only `Employee` is defined inside `model` package. How can I fix it? Thank you

**Comment by vincentlauvlwj** [comment]
Checkout to this version: 

```sh
git checkout f0e7fc62
```

Then run the build: 

```sh
./gradlew clean build
```

**Comment by weifengze** [comment]
org.ktorm:ktorm-ksp-annotations:3.7.0-SNAPSHOT 什么时候发布到maven中央仓库

**Comment by vincentlauvlwj** [comment]
> org.ktorm:ktorm-ksp-annotations:3.7.0-SNAPSHOT 什么时候发布到maven中央仓库

最新版 4.0.0 已发布

**Comment by vincentlauvlwj** [comment]
Fixed
